version: '3.9'

services:
  redis:
    container_name: redis
    restart: on-failure
    image: redis
    ports:
      - 6379:6379

  postgres:
    container_name: postgres
    image: postgres
    restart: on-failure
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "rental"
    ports:
      - 5432:5432
    depends_on:
      - redis

  app:
    build: ./
    container_name: app
    command: bash entrypoint.sh
    volumes:
      - ./static:/static
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - postgres

  nginx:
    container_name: nginx
    build: ./nginx
    volumes:
      - ./static:/static
    ports:
      - 80:80
    depends_on:
      - app

  celery:
    container_name: celery
    build: ./
    command: celery -A core worker -l info
    depends_on:
      - nginx

volumes:
  postgres_data:
