# Generated by Django 5.0.6 on 2024-07-02 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bicycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=25, verbose_name='Модель велосипеда')),
                ('price', models.PositiveSmallIntegerField(verbose_name='Цена за час')),
                ('status', models.CharField(choices=[('rented', 'Арендован'), ('free', 'Свободен')], default='free', max_length=9, verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_start', models.DateTimeField(auto_now_add=True, verbose_name='Начало аренды')),
                ('rent_finish', models.DateTimeField(verbose_name='Конец аренды')),
                ('total_price', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Сумма аренды')),
                ('bicycle', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bicycle', to='rental.bicycle', verbose_name='Велосипед')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Арендатор')),
            ],
        ),
    ]
