# Generated by Django 5.1.3 on 2024-11-15 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bicycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=25, verbose_name='Модель велосипеда')),
                ('price', models.PositiveSmallIntegerField(verbose_name='Цена за час')),
                ('status', models.CharField(choices=[('rented', 'Арендован'), ('free', 'Свободен')], default='free', max_length=9, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Велосипед',
                'verbose_name_plural': 'Велосипеды',
                'ordering': ['status', '-price'],
                'indexes': [models.Index(fields=['-model'], name='rental_bicy_model_b96754_idx')],
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_start', models.DateTimeField(auto_now_add=True, verbose_name='Начало аренды')),
                ('rent_finish', models.DateTimeField(blank=True, null=True, verbose_name='Конец аренды')),
                ('total_price', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Сумма аренды')),
                ('bicycle', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bicycle', to='rental.bicycle', verbose_name='Велосипед')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Арендатор')),
            ],
            options={
                'verbose_name': 'История заказов',
                'verbose_name_plural': 'История заказов',
                'ordering': ['rent_start'],
                'indexes': [models.Index(fields=['-user'], name='rental_orde_user_id_0940e8_idx')],
            },
        ),
    ]
