# Generated by Django 5.0.6 on 2024-07-02 19:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bicycle',
            options={'ordering': ['status', '-price'], 'verbose_name': 'Велосипед', 'verbose_name_plural': 'Велосипеды'},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'ordering': ['rent_start'], 'verbose_name': 'История заказов', 'verbose_name_plural': 'История заказов'},
        ),
        migrations.AddIndex(
            model_name='bicycle',
            index=models.Index(fields=['-model'], name='rental_bicy_model_b96754_idx'),
        ),
        migrations.AddIndex(
            model_name='orders',
            index=models.Index(fields=['-user'], name='rental_orde_user_id_0940e8_idx'),
        ),
    ]
